version: 0.0
os: linux
files:
  - source: main
    destination: /opt/go-app
  - source: config/config.yaml
    destination: /opt/go-app/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh # Stop old service, clean directory
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh # Set permissions, copy systemd unit file (optional)
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh # Start the systemd service
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh # Stop the systemd service (called before BeforeInstall on updates)
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh # Check if the app is running ok
      timeout: 60
      runas: root
