FROM golang:1.24.0-alpine

RUN apk add --no-cache entr

#Create a user with UID 1000 and GID 1000 (match your host user)
RUN addgroup -g 1000 appuser && \
    adduser -D -u 1000 -G appuser appuser

USER appuser


WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

USER root
RUN chown -R appuser:appuser .
RUN chmod -R 744 .


USER appuser
CMD ["sh", "/app/watch.sh"]
