# Application Configuration
app:
  name: "Arabkood"
  environment: "development"
  baseURL: "http://alpha.akood.com"
  debug: true

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  corsOrigins:
    - "http://alpha.akood.com"
    - "https://alpha.akood.com"
  readTimeout: "15s"
  writeTimeout: "15s"
  gracefulTimeout: "15s"
  internalAllowList:
    - "10.0.0.0/8"
  internalAuthSecret: "HelloWorld"

# Database Configuration
database:
  host: ""
  port: 5432
  username: "postgres"
  password: ""
  name: "arabkood_0"
  sslMode: "disable"
  # Connection pool settings
  maxConnLifetime: "1h"
  maxConnLifetimeJitter: "5m"
  maxConnIdleTime: "30m"
  maxConns: 25
  minConns: 5
  healthCheckPeriod: "5m"

# Authentication Configuration
auth:
  cookiesDomains:
    - "alpha.akood.com"
    # - "dev.arabkood.com"
    # - "dev.akood.com"
    # - "localhost"
    # - "arabkood.com"
  sessionCookieName: "arabkood_session_token"
  sessionTokenExpiryHours: 720 # 30 days
  emailVerificationExpiryMinutes: 1440 # 24 hours
  emailVerificationCodeLength: 6
  emailVerificationCodeChars: "0123456789"
  passwordResetExpiryMinutes: 60 # 1 hour
  passwordResetCodeLength: 6
  passwordResetCodeChars: "0123456789"

email:
  provider: "smtp"
  fromEmail: "noreply@arabkood.com"
  fromName: "Arabkood"
  smtpHost: "email-smtp.eu-north-1.amazonaws.com"
  smtpPort: "465"
  smtpUser: "AKIAV7C53RKI7IPCOSJI"
  smtpPass: "BLz94aN/CUfmJu+pUdqI4Z/ysNXIg3wirU7U7HWz4zlP"

aws:
  region: "me-south-1"
  submissionQueueURL: "https://localhost.localstack.cloud:4566/000000000000/Main_Runner_Queue"
  credentialsPath: "/.aws/credentials"
  profile: "dev"
  endpoint: "http://172.17.0.1:4566"
  topicsBucketName: "kood-topics-bucket"
  logGroupName: "/ecs/ArabKood-Backend-dev"

other:
  submissionsDirectory: "/mnt/submissions/"
